pipeline {	
    // Run pipeline on master node 
	agent  {
		label 'maven'
	}
    
    stages {
        // Stage1 Clone Source Code
        stage('Clone Source Code') {
            steps {
            	echo 'Clone Source Code ...'
				git branch: 'main', url: 'https://github.com/j3ffk3/nccu-lab-2020.git'
            }
        }
		
		// Stage2 Unit Test
        stage('Unit Test') {
            steps {
            	dir("recommendation") {
					sh """
				 		mvn test
					"""
				}
            }
        }
		
		// Stage3 Code Quality Analysis
        stage('Code Quality Analysis') {
            steps {
            	dir("recommendation") {
					sh """
						mvn clean package sonar:sonar -Dsonar.projectKey=recommendation-jeff -Dsonar.projectName=jeff-recommendation
					"""
				}
            }
        }
		
		// Stage4 Build Jar file
        stage('Build Jar file') {
            steps {
            	dir("recommendation") {
					sh """
						mvn clean package -DskipTests
					"""
				}
            }
        }
		
		
		// Stage5 Build Image
        stage('Build Image & Deploy') {
            steps {
            	dir("recommendation/target") {
					sh """
						oc project jeff
						oc start-build bc/recommendation --from-file recommendation-0.0.1-SNAPSHOT.jar -F
					"""
				}
			}
		}
	}
}