pipeline {	
    // Run pipeline on master node 
	agent  {
		label 'maven'
	}
    
    stages {
        // Stage1 Clone Source Code
        stage('Clone Source Code') {
            steps {
            	echo 'Clone Source Code ...'
				git branch: '${GIT_BRANCH}', url: '${GIT_URL}'
            }
        }
		
		// Stage2 Unit Test
        stage('Unit Test') {
            steps {
				sh """
				 	mvn test
				"""
            }
        }
		
		// Stage3 Code Quality Analysis
        stage('Code Quality Analysis') {
            steps {
				sh """
					mvn sonar:sonar -Dsonar.projectKey=recommendation-jeff -Dsonar.projectName=jeff-recommendation
				"""
            }
        }
		
		// Stage4 Build Jar file
        stage('Build Jar file') {
            steps {
				sh """
					mvn clean package
				"""
            }
        }
		
		
		// Stage5 Build Image
        stage('Build Image & Deploy') {
            steps {
            	dir("target") {
					sh """
						oc project jeff
						oc start build bc/recommendation --from-file recommendation-0.0.1-SNAPSHOT.jar
					"""
				}
			}
		}
	}
}